### ISSUE TITLE
你好，你的 这个东西写得很多

### ISSUE THREAD

**Issue by wy19901227** [DaidoujiChen/DaiNavigationTransition#2]
但是有个问题就是， 如果我设置了导航栏的代理的话，你这个就不起作用了，。还有个问题就是，这个是ios7出得新api，那么ios7之前是怎么样做得，是在导航控制器代理方法里实现的嘛？ 请问 你有ios7之前实现的demo嘛？ 我必须要适配到ios6，谢谢了。

**Comment by DaidoujiChen** [comment]
Hello @wy19901227,

第一個, 對的, 如果你有設置了其他方法, 可能使用上就會有問題.
第二個, 當初 ios8 還沒有出的時候我有驗過 6 和 7, 雖然不到完全完全的一樣, 
不過可以看得出來這個效果, 現在我也沒有辦法 demo ios6 了, sorry, 不對! 應該跟你主管說,
不用再支援 ios6 了, 哈哈.

**Comment by wy19901227** [comment]
你好，   我设置代理  是在第一级push的  时候 有个需求要处理，然后 到第二级是你这个需求，所以我在viewdiddisappear的时候把导航控制器的代理赋值为nil，可是 转场效果并没有出现，请问 ，您可以解决下这个问题吗？  还有就是我想提个建议，你可以扩展下  把fromview 和toview做为一个数组，来push多个需要转场的动画。您写得runtime这个东西 我看着有点头疼，自己改不了，嘿嘿。

**Comment by wy19901227** [comment]
我已经  解决了 这个代理问题了，你这个项目真得很好，通过你这个可以学习如何转场（原理），ios6和以后，更重要的是，你的封装思想值得学习，希望你可以完善这个项目。

**Comment by DaidoujiChen** [comment]
O口O" 我還沒有時間看開始想~你就已經解完了!!
不過有幫助到你的話就好了~
