### ISSUE TITLE
ios6的问题

### ISSUE THREAD

**Issue by wy19901227** [DaidoujiChen/DaiNavigationTransition#3]
突然发现个问题，我要适配到ios6，还没在ios6上跑过，但是 你的api里有ios7才有的api，那跑在ios6上，不是会直接蹦了嘛？

**Comment by DaidoujiChen** [comment]
Hello @wy19901227,

我現在也沒有辦法驗證 ios6 了, 如果你還有 6 的機器或是模擬器, 你可以先試試看,
就當初我在驗證的時候, 這個部分是沒有問題的, 我們有實際的把這個項目, 使用在我們商業項目裡,
從 code 說起來的話, 我隨便舉一個段落的例子

```
- (void)swizzling_pushViewController:(UIViewController *)viewController animated:(BOOL)animated
{
    [DaiNavigationTransition objects].isPush = YES;

    //if ios version > 7.0, just do nothing
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0f) {
        [self swizzling_pushViewController:viewController animated:animated];
    } else {

        if (animated) {
            NSDictionary *preProcessDictionary = [self preProcessAnimation];
            [self swizzling_pushViewController:viewController animated:NO];
            [self sufProcessAnimation:preProcessDictionary];
        } else {
            [self swizzling_pushViewController:viewController animated:animated];
        }
    }
}
```

在 ios7 以上的時候, 把 `UINavigationControllerDelegate` 裡面才有

```
- (id <UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController *)fromVC toViewController:(UIViewController* )toVC;
```

這個 method, 所以在 ios7 以下, 是不會進來這邊的, 因此, 在 ios7 以上時, 直接走原來的 `pushViewController:animated:` 就會走進這個 method, 進而產生動畫效果.

在 ios6 的時候, 這個 method 並不會被運行, 所以我繞了一個遠路, 簡單的說, 我是手動的把前後兩個畫面截圖, 再讓選定的 view 移動過去, 替代 ios7 會自動做掉的那一段.

大概是這個樣子.

**Comment by wy19901227** [comment]
我运行了，是没有问题，你做得非常棒，但是我不明白的是
 UIViewController *fromViewController = [transitionContext viewControllerForKey:UITransitionContextFromViewControllerKey];
    UIViewController *toViewController = [transitionContext viewControllerForKey:UITransitionContextToViewControllerKey];

其中 UITransitionContextFromViewControllerKey 这个是ios7才定义的常量，运行在ios6上为什么没事呢？

**Comment by DaidoujiChen** [comment]
Hello @wy19901227,

因為根本不會跑到那邊喔!

**Comment by wy19901227** [comment]
我是用真机测试的，代码是不会跑到那里去，但是 你编译的 时候 ios6的sdk  无法 识别 ios7才有的api啊，可是为什么能跑起来？

**Comment by DaidoujiChen** [comment]
Hello @wy19901227,

![2015-05-15 12 37 32](https://cloud.githubusercontent.com/assets/670441/7646980/3c261f0c-faff-11e4-9e62-1109f12a6ae7.png)

左邊的 iOS SDK 只要認識就可以.

**Comment by wy19901227** [comment]
原来如此  我了解了   编译和xcode的sdk有关

**Comment by DaidoujiChen** [comment]
嗯嗯
