### ISSUE TITLE
好晕哦

### ISSUE THREAD

**Issue by wy19901227** [DaidoujiChen/DaiNavigationTransition#4]
还有个问题就是 在你这个类下，导航控制器只能有两种转场方式，一种默认的，一种就是这样特效的，但是可能存在其他的需求，就需要覆盖代理操作。ios7下可以覆盖，但是ios6下 ，你写死了，不能覆盖了。
所以 ，能不能也覆盖？

**Comment by wy19901227** [comment]
也可以这样 说 ，就是  你能不能把ios6下自己实现的push方式放在 代理方法里，像这两个方法里边

-(void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated

-(void)navigationController:(UINavigationController *)navigationController didShowViewController:(UIViewController *)viewController animated:(BOOL)animated

这样，我就可以写自己的转场了。

你自己写得ios6下得默认push效果，我这里有个需求，加上去的话，就会有个bug，

**Comment by wy19901227** [comment]
这个需求就是，类似于微博，qq等  在tabbar控制器中，每个子控制器点击的时候，想让这个tabbar像是在此自控制器的上边一样，随着控制器一起被push过去，不知道我这个需求 描述的 你能明白吗？

在ios6的情况下，我把需求写在代理里，但是你自己写得默认push效果 依然在运行，就会出现不好的情况，  在ios7下没问题，因为我没运行你在ios7下写得默认push效果

**Comment by DaidoujiChen** [comment]
Hello @wy19901227,

目前有幾個難點...
第一個, 就是我沒有辦法測 ios6...
第二個, 這個功能是當初為了讓 ios6 與 ios7 都可以有一樣的效果, 所以在 6 上硬刻出來的,
那時候我只有想做的跟 7 一樣的目的而已. 所以這邊我可能沒有辦法幫你.

**Comment by wy19901227** [comment]
好吧，还是谢谢 你

**Comment by DaidoujiChen** [comment]
不會, 客氣.
